### ISSUE TITLE
school filter

### ISSUE THREAD

**Issue by 2014CAIS01** [XCPCIO/XCPCIO-board#1]
在比赛榜单中筛选学校后，左侧排名和奖牌情况显示不是很合理，没有显示其实际排名和奖牌。

**Comment by Dup4** [comment]
> 在比赛榜单中筛选学校后，左侧排名和奖牌情况显示不是很合理，没有显示其实际排名和奖牌。

- 确实不合理。我也注意到了这个问题。
- 我准备将 「关注的队伍」，「通过学校筛选的队伍」像 DOMjudge 榜单中的关注效果类似，在榜单的最前面显示一份，并且排名和奖牌情况是基于当前 Group 整体数据的。 
- 这个 Group 其实在 CCPC 中体现不出来，可以参考浙江省赛的 「本科组」，「专科组」。
- 但是目前遇到另外一个问题，这件事情就暂时先搁置了。
- 这个问题是，因为我想再做一个功能，就是拖动进度条，然后复现比赛中某个时刻的榜单。
- 然后对于拿到的榜单数据，目前有两种类型。一种是每支队伍的每道题的 AC 情况(譬如：PTA榜单)，还有一种是每一发提交的情况(譬如：浙江省赛榜单)。
- 然后之前我是想统一一下类型，就是将前者统一到后者，对于一道题目，有 x 发提交，AC 时间为 y 的题目，我拆成 (x - 1) 发 AC 时间为 y 的 incorrect 提交以及 1 发 AC 时间为 y 的 correct 提交。
- 因为提供每一发提交情况的榜单，能够更精确的复现某一时刻的榜单，因为每一发 WA 的时间都有。
- 但是在 CCPC 威海站的榜单中，我发现 PTA 榜单中，AC 之后的提交也会计入 tries, 那么这个时候根据我的 「拆法」，罚时的计算就不对了。
- 所以我可能需要重构一部分，使得支持这两种情况，所以需要搁置一下，不过争取在绵阳站之前完成。
- 不过我有一个问题，蔡队你知道开火车榜单中的 Dirt 和 SE 分别代表什么吗。

![image](https://user-images.githubusercontent.com/38343778/97246216-c3ab8d80-1837-11eb-870f-25d88e433207.png)

- 对于每支队伍的 Dirt，我推测可能是 非AC数 / 总提交数。

![image](https://user-images.githubusercontent.com/38343778/97246286-f2296880-1837-11eb-94be-3db8eed8e163.png)

- 但是对于每道题的 Dirt，我发现不符合。

**Comment by 2014CAIS01** [comment]
Dirt 的确是非AC数 / 总提交数。

SE 的话，我的理解是队伍做出的题目的含金量，是个动态变化的值。

可以发现在同题数的队伍中，一个队伍如果通过了一个较少的人过的题，这个队伍的SE就会比其他队伍多一些，但具体计算方式我不太清楚。

**Comment by 2014CAIS01** [comment]
所以每个题的 dirt 在计算的时候不能直接用总提交数，因为总的提交数包含了未通过这个题的队伍的提交，但是不能算在 dirt 里面。

**Comment by Dup4** [comment]
> 所以每个题的 dirt 在计算的时候不能直接用总提交数，因为总的提交数包含了未通过这个题的队伍的提交，但是不能算在 dirt 里面。

有道理，我去改一下。:smile:

**Comment by Dup4** [comment]
> 所以每个题的 dirt 在计算的时候不能直接用总提交数，因为总的提交数包含了未通过这个题的队伍的提交，但是不能算在 dirt 里面。

但是每道题的 Accepted 率和 Dirt 率 加起来并不是 100%。

所以应该是：
- Accepted 率的计算是 AC的提交 / 总提交
- Dirt 率是 通过这道题的那些队伍的非AC的提交 / 通过这道题的那些队伍的所有提交

这样吗?
