### ISSUE TITLE
希望添加 board.acmicpc.info 上的榜单

### ISSUE THREAD

**Issue by nocrizwang** [XCPCIO/XCPCIO-Board#3]
@Dup4 board.acmicpc.info上有格式较为统一、数据也很齐全的榜单，能否导入？是否有空做此事？您没有空的话，应当如何操作才能导入这些榜单？

例：
http://board.acmicpc.info/icpc2016/dlmu_onsite.php

似乎2016年之前都很全。导入这些榜单之后，再补补17-18年的榜单，网站上就可以有所有榜单了！ 

我觉得这是一项很伟大的事业。

**Comment by Dup4** [comment]
嗯，这件事在计划中。

主要是目前可能数据格式还会稍有变动，所以想稳定下来再整 acmicoc.info 上的榜单。

我最近赶下进度，先把数据格式相关的文档先出了，这样大家想一起帮忙的话应该也会比较好入手。

**Comment by nocrizwang** [comment]
好，期待

**Comment by nocrizwang** [comment]
board.acmicpc.info 没了

这下图图了

**Comment by nocrizwang** [comment]
不知道现在怎么办，本来那个网站收集的那么好。

**Comment by YangDong2002** [comment]
还有救 https://web.archive.org/web/20180228124035/http://board.acmicpc.info/icpc2016/dlmu_online.php

**Comment by Dup4** [comment]
感谢 @baooom 的贡献，我们基本补全了 acmicpc.info 上的榜单。

相关的 PR 如下：

- https://github.com/XCPCIO/XCPCIO-Board-Data/pull/1
- https://github.com/XCPCIO/XCPCIO-Board-Spider/pull/1
